// Code generated by protoc-gen-go. DO NOT EDIT.
// source: codecs_test.proto

package test

import (
	fmt "fmt"
	pmongo "github.com/amsokol/mongo-go-driver-protobuf/pmongo"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	wrappers "github.com/golang/protobuf/ptypes/wrappers"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Data struct {
	BoolValue            *wrappers.BoolValue   `protobuf:"bytes,1,opt,name=boolValue,proto3" json:"boolValue,omitempty"`
	BytesValue           *wrappers.BytesValue  `protobuf:"bytes,2,opt,name=bytesValue,proto3" json:"bytesValue,omitempty"`
	DoubleValue          *wrappers.DoubleValue `protobuf:"bytes,3,opt,name=doubleValue,proto3" json:"doubleValue,omitempty"`
	FloatValue           *wrappers.FloatValue  `protobuf:"bytes,4,opt,name=floatValue,proto3" json:"floatValue,omitempty"`
	Int32Value           *wrappers.Int32Value  `protobuf:"bytes,5,opt,name=int32Value,proto3" json:"int32Value,omitempty"`
	Int64Value           *wrappers.Int64Value  `protobuf:"bytes,6,opt,name=int64Value,proto3" json:"int64Value,omitempty"`
	StringValue          *wrappers.StringValue `protobuf:"bytes,7,opt,name=stringValue,proto3" json:"stringValue,omitempty"`
	Uint32Value          *wrappers.UInt32Value `protobuf:"bytes,8,opt,name=uint32Value,proto3" json:"uint32Value,omitempty"`
	Uint64Value          *wrappers.UInt64Value `protobuf:"bytes,9,opt,name=uint64Value,proto3" json:"uint64Value,omitempty"`
	Timestamp            *timestamp.Timestamp  `protobuf:"bytes,10,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Id                   *pmongo.ObjectId      `protobuf:"bytes,11,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *Data) Reset()         { *m = Data{} }
func (m *Data) String() string { return proto.CompactTextString(m) }
func (*Data) ProtoMessage()    {}
func (*Data) Descriptor() ([]byte, []int) {
	return fileDescriptor_b2b3e361c7bc6717, []int{0}
}

func (m *Data) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Data.Unmarshal(m, b)
}
func (m *Data) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Data.Marshal(b, m, deterministic)
}
func (m *Data) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Data.Merge(m, src)
}
func (m *Data) XXX_Size() int {
	return xxx_messageInfo_Data.Size(m)
}
func (m *Data) XXX_DiscardUnknown() {
	xxx_messageInfo_Data.DiscardUnknown(m)
}

var xxx_messageInfo_Data proto.InternalMessageInfo

func (m *Data) GetBoolValue() *wrappers.BoolValue {
	if m != nil {
		return m.BoolValue
	}
	return nil
}

func (m *Data) GetBytesValue() *wrappers.BytesValue {
	if m != nil {
		return m.BytesValue
	}
	return nil
}

func (m *Data) GetDoubleValue() *wrappers.DoubleValue {
	if m != nil {
		return m.DoubleValue
	}
	return nil
}

func (m *Data) GetFloatValue() *wrappers.FloatValue {
	if m != nil {
		return m.FloatValue
	}
	return nil
}

func (m *Data) GetInt32Value() *wrappers.Int32Value {
	if m != nil {
		return m.Int32Value
	}
	return nil
}

func (m *Data) GetInt64Value() *wrappers.Int64Value {
	if m != nil {
		return m.Int64Value
	}
	return nil
}

func (m *Data) GetStringValue() *wrappers.StringValue {
	if m != nil {
		return m.StringValue
	}
	return nil
}

func (m *Data) GetUint32Value() *wrappers.UInt32Value {
	if m != nil {
		return m.Uint32Value
	}
	return nil
}

func (m *Data) GetUint64Value() *wrappers.UInt64Value {
	if m != nil {
		return m.Uint64Value
	}
	return nil
}

func (m *Data) GetTimestamp() *timestamp.Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

func (m *Data) GetId() *pmongo.ObjectId {
	if m != nil {
		return m.Id
	}
	return nil
}

func init() {
	proto.RegisterType((*Data)(nil), "test.Data")
}

func init() { proto.RegisterFile("codecs_test.proto", fileDescriptor_b2b3e361c7bc6717) }

var fileDescriptor_b2b3e361c7bc6717 = []byte{
	// 319 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0xd2, 0xcf, 0x4b, 0xc3, 0x30,
	0x14, 0xc0, 0x71, 0x36, 0xb7, 0xe9, 0xb2, 0x8b, 0x16, 0x84, 0x31, 0x45, 0x87, 0x27, 0x4f, 0x19,
	0x6c, 0x22, 0x82, 0xe0, 0x41, 0x86, 0xb0, 0x93, 0x10, 0x7f, 0x5c, 0x25, 0x59, 0xb2, 0x12, 0x69,
	0xfb, 0x4a, 0x93, 0x22, 0xfe, 0x17, 0xfe, 0xc9, 0x92, 0xa4, 0x69, 0x83, 0x23, 0xde, 0x46, 0xf7,
	0xfd, 0x24, 0x2f, 0xf0, 0xd0, 0xc9, 0x16, 0xb8, 0xd8, 0xaa, 0x0f, 0x2d, 0x94, 0xc6, 0x65, 0x05,
	0x1a, 0x92, 0x81, 0xf9, 0x3d, 0xbb, 0x4c, 0x01, 0xd2, 0x4c, 0x2c, 0xec, 0x37, 0x56, 0xef, 0x16,
	0x5a, 0xe6, 0x42, 0x69, 0x9a, 0x97, 0x2e, 0x9b, 0x5d, 0xfc, 0x0d, 0xbe, 0x2a, 0x5a, 0x96, 0xa2,
	0x52, 0xcd, 0xff, 0xa7, 0x65, 0x0e, 0x45, 0x0a, 0x0b, 0x60, 0x9f, 0x62, 0xab, 0x25, 0x77, 0x9f,
	0xaf, 0x7e, 0x86, 0x68, 0xb0, 0xa6, 0x9a, 0x26, 0x77, 0x68, 0xcc, 0x00, 0xb2, 0x77, 0x9a, 0xd5,
	0x62, 0xda, 0x9b, 0xf7, 0xae, 0x27, 0xcb, 0x19, 0x76, 0x67, 0x62, 0x7f, 0x26, 0x7e, 0xf4, 0x05,
	0xe9, 0xe2, 0xe4, 0x1e, 0x21, 0xf6, 0xad, 0x85, 0x72, 0xb4, 0x6f, 0xe9, 0xd9, 0x3e, 0x6d, 0x13,
	0x12, 0xe4, 0xc9, 0x03, 0x9a, 0x70, 0xa8, 0x59, 0x26, 0x9c, 0x3e, 0xb0, 0xfa, 0x7c, 0x4f, 0xaf,
	0xbb, 0x86, 0x84, 0xc0, 0x5c, 0xbe, 0xcb, 0x80, 0x6a, 0xc7, 0x07, 0x91, 0xcb, 0x9f, 0xda, 0x84,
	0x04, 0xb9, 0xc1, 0xb2, 0xd0, 0xab, 0xa5, 0xc3, 0xc3, 0x08, 0xde, 0xb4, 0x09, 0x09, 0xf2, 0x06,
	0xdf, 0xde, 0x38, 0x3c, 0x8a, 0xe3, 0x26, 0x21, 0x41, 0x6e, 0x9e, 0xad, 0x74, 0x25, 0x8b, 0xd4,
	0xe9, 0xc3, 0xc8, 0xb3, 0x5f, 0xba, 0x86, 0x84, 0xc0, 0xf8, 0x3a, 0x18, 0xfd, 0x28, 0xe2, 0xdf,
	0x82, 0xd9, 0x43, 0xe0, 0xbd, 0x9f, 0x7e, 0xfc, 0x8f, 0xf7, 0xe3, 0x87, 0xc0, 0x6c, 0x4b, 0xbb,
	0x80, 0x53, 0x14, 0xd9, 0x96, 0x57, 0x5f, 0x90, 0x2e, 0x4e, 0xe6, 0xa8, 0x2f, 0xf9, 0x74, 0x62,
	0xc9, 0x31, 0x76, 0x4b, 0x89, 0x9f, 0xed, 0x52, 0x6e, 0x38, 0xe9, 0x4b, 0xce, 0x46, 0xf6, 0x80,
	0xd5, 0x6f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x39, 0xb1, 0xfa, 0xb9, 0x0c, 0x03, 0x00, 0x00,
}
