// Code generated by protoc-gen-go. DO NOT EDIT.
// source: codecs_test.proto

package codecs

import (
	fmt "fmt"
	mongodb "github.com/amsokol/mongo-go-driver-protobuf/mongodb"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	wrappers "github.com/golang/protobuf/ptypes/wrappers"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type TestData struct {
	BoolValue            *wrappers.BoolValue   `protobuf:"bytes,1,opt,name=boolValue,proto3" json:"boolValue,omitempty"`
	BytesValue           *wrappers.BytesValue  `protobuf:"bytes,2,opt,name=bytesValue,proto3" json:"bytesValue,omitempty"`
	DoubleValue          *wrappers.DoubleValue `protobuf:"bytes,4,opt,name=doubleValue,proto3" json:"doubleValue,omitempty"`
	FloatValue           *wrappers.FloatValue  `protobuf:"bytes,5,opt,name=floatValue,proto3" json:"floatValue,omitempty"`
	Int32Value           *wrappers.Int32Value  `protobuf:"bytes,6,opt,name=int32Value,proto3" json:"int32Value,omitempty"`
	Int64Value           *wrappers.Int64Value  `protobuf:"bytes,7,opt,name=int64Value,proto3" json:"int64Value,omitempty"`
	StringValue          *wrappers.StringValue `protobuf:"bytes,8,opt,name=stringValue,proto3" json:"stringValue,omitempty"`
	Uint32Value          *wrappers.UInt32Value `protobuf:"bytes,9,opt,name=uint32Value,proto3" json:"uint32Value,omitempty"`
	Uint64Value          *wrappers.UInt64Value `protobuf:"bytes,10,opt,name=uint64Value,proto3" json:"uint64Value,omitempty"`
	Timestamp            *timestamp.Timestamp  `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Id                   *mongodb.ObjectId     `protobuf:"bytes,11,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *TestData) Reset()         { *m = TestData{} }
func (m *TestData) String() string { return proto.CompactTextString(m) }
func (*TestData) ProtoMessage()    {}
func (*TestData) Descriptor() ([]byte, []int) {
	return fileDescriptor_b2b3e361c7bc6717, []int{0}
}

func (m *TestData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TestData.Unmarshal(m, b)
}
func (m *TestData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TestData.Marshal(b, m, deterministic)
}
func (m *TestData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TestData.Merge(m, src)
}
func (m *TestData) XXX_Size() int {
	return xxx_messageInfo_TestData.Size(m)
}
func (m *TestData) XXX_DiscardUnknown() {
	xxx_messageInfo_TestData.DiscardUnknown(m)
}

var xxx_messageInfo_TestData proto.InternalMessageInfo

func (m *TestData) GetBoolValue() *wrappers.BoolValue {
	if m != nil {
		return m.BoolValue
	}
	return nil
}

func (m *TestData) GetBytesValue() *wrappers.BytesValue {
	if m != nil {
		return m.BytesValue
	}
	return nil
}

func (m *TestData) GetDoubleValue() *wrappers.DoubleValue {
	if m != nil {
		return m.DoubleValue
	}
	return nil
}

func (m *TestData) GetFloatValue() *wrappers.FloatValue {
	if m != nil {
		return m.FloatValue
	}
	return nil
}

func (m *TestData) GetInt32Value() *wrappers.Int32Value {
	if m != nil {
		return m.Int32Value
	}
	return nil
}

func (m *TestData) GetInt64Value() *wrappers.Int64Value {
	if m != nil {
		return m.Int64Value
	}
	return nil
}

func (m *TestData) GetStringValue() *wrappers.StringValue {
	if m != nil {
		return m.StringValue
	}
	return nil
}

func (m *TestData) GetUint32Value() *wrappers.UInt32Value {
	if m != nil {
		return m.Uint32Value
	}
	return nil
}

func (m *TestData) GetUint64Value() *wrappers.UInt64Value {
	if m != nil {
		return m.Uint64Value
	}
	return nil
}

func (m *TestData) GetTimestamp() *timestamp.Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

func (m *TestData) GetId() *mongodb.ObjectId {
	if m != nil {
		return m.Id
	}
	return nil
}

func init() {
	proto.RegisterType((*TestData)(nil), "codecs.TestData")
}

func init() { proto.RegisterFile("codecs_test.proto", fileDescriptor_b2b3e361c7bc6717) }

var fileDescriptor_b2b3e361c7bc6717 = []byte{
	// 323 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0xd2, 0x4f, 0x4b, 0xfb, 0x30,
	0x18, 0xc0, 0x71, 0xb6, 0xdf, 0x6f, 0x73, 0xcb, 0x4e, 0xeb, 0x41, 0xc6, 0x14, 0xff, 0x9d, 0x3c,
	0x65, 0xb0, 0x89, 0x08, 0x82, 0x07, 0x19, 0xc2, 0x4e, 0x42, 0x9c, 0x5e, 0x25, 0x59, 0xb2, 0x12,
	0xe9, 0xf6, 0x94, 0xe6, 0x29, 0xe2, 0x0b, 0xf1, 0xfd, 0x4a, 0x93, 0xa6, 0x0d, 0x8e, 0x78, 0x4d,
	0xbf, 0x9f, 0xf4, 0x09, 0x3c, 0x64, 0xbc, 0x01, 0xa9, 0x36, 0xe6, 0x1d, 0x95, 0x41, 0x9a, 0x17,
	0x80, 0x90, 0xf4, 0xdd, 0xd1, 0xf4, 0x3c, 0x05, 0x48, 0x33, 0x35, 0xb3, 0xa7, 0xa2, 0xdc, 0xce,
	0x50, 0xef, 0x94, 0x41, 0xbe, 0xcb, 0x5d, 0x38, 0x3d, 0xfb, 0x1d, 0x7c, 0x16, 0x3c, 0xcf, 0x55,
	0x61, 0xea, 0xef, 0xc7, 0x3b, 0xd8, 0xa7, 0x20, 0xc5, 0x0c, 0xc4, 0x87, 0xda, 0xa0, 0x96, 0xee,
	0xfc, 0xea, 0xbb, 0x47, 0x06, 0x6b, 0x65, 0x70, 0xc9, 0x91, 0x27, 0x77, 0x64, 0x28, 0x00, 0xb2,
	0x37, 0x9e, 0x95, 0x6a, 0xd2, 0xb9, 0xe8, 0x5c, 0x8f, 0xe6, 0x53, 0xea, 0x2e, 0xa6, 0xfe, 0x62,
	0xfa, 0xe8, 0x0b, 0xd6, 0xc6, 0xc9, 0x3d, 0x21, 0xe2, 0x0b, 0x95, 0x71, 0xb4, 0x6b, 0xe9, 0xc9,
	0x21, 0x6d, 0x12, 0x16, 0xe4, 0xc9, 0x03, 0x19, 0x49, 0x28, 0x45, 0xa6, 0x9c, 0xfe, 0x6f, 0xf5,
	0xe9, 0x81, 0x5e, 0xb6, 0x0d, 0x0b, 0x41, 0xf5, 0xf3, 0x6d, 0x06, 0x1c, 0x1d, 0xef, 0x45, 0x7e,
	0xfe, 0xd4, 0x24, 0x2c, 0xc8, 0x2b, 0xac, 0xf7, 0xb8, 0x98, 0x3b, 0xdc, 0x8f, 0xe0, 0x55, 0x93,
	0xb0, 0x20, 0xaf, 0xf1, 0xed, 0x8d, 0xc3, 0x47, 0x71, 0x5c, 0x27, 0x2c, 0xc8, 0xab, 0x67, 0x1b,
	0x2c, 0xf4, 0x3e, 0x75, 0x7a, 0x10, 0x79, 0xf6, 0x4b, 0xdb, 0xb0, 0x10, 0x54, 0xbe, 0x0c, 0x46,
	0x1f, 0x46, 0xfc, 0x6b, 0x30, 0x7b, 0x08, 0xbc, 0xf7, 0xd3, 0x93, 0x3f, 0xbc, 0x1f, 0x3f, 0x04,
	0xd5, 0xb6, 0x34, 0x5b, 0x38, 0xf9, 0x17, 0xd9, 0x96, 0xb5, 0x2f, 0x58, 0x1b, 0x27, 0x97, 0xa4,
	0xab, 0xe5, 0x64, 0x64, 0xc9, 0x98, 0xd6, 0x9b, 0x49, 0x9f, 0xed, 0x66, 0xae, 0x24, 0xeb, 0x6a,
	0x29, 0xfa, 0xf6, 0x86, 0xc5, 0x4f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x77, 0x7b, 0x50, 0x91, 0x14,
	0x03, 0x00, 0x00,
}
